#!/usr/bin/env perl

use strict;
use warnings;

use AnyEvent;
use FindBin '$Bin';

use JLogger;
use JLogger::Config;

$0 = 'jlogger';

my $cv = AnyEvent->condvar;

my $config_file = '/etc/jlogger.yaml';
if (@ARGV > 0) {
    $config_file = $ARGV[0];
}

my $config = JLogger::Config->new->load_file($config_file);
my $logger = JLogger->new(%$config);

$logger->connect;

$cv->recv;
